---
title: "viz"
author: "Terra Alpaugh"
date: "April 16, 2016"
output: html_document
---

##Scatterplot
```{r load, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(gapminder)

#preview data
gapminder

# get a range of available data
summary(gapminder)
```


```{r}
# setup dataframe
g = gapminder %>%
  filter(year==2007) %>%   # most recent year 
  mutate(pop_m = pop/1e6)  # population, millions

# plot scatterplot of most recent year 
s = ggplot(g, aes(x=gdpPercap, y=lifeExp)) +
  geom_point() #ggplot takes a dataframe; then aes(specifically what you're looking at); then type of plot
s 

# add aesthetic of size by population
s = s + 
  aes(size=pop_m)
s
#add aesthetic of color by continent
s = s + 
  aes(color=continent)
s

ggsave('hans.png')

#add axes, title
s = s + 
  ggtitle('Health & Wealth of Nations for 2007') +
  xlab('GDP per capita ($/year)') +
  ylab('Life expectancy (years)')
s

# label legend
s = s + 
  scale_colour_discrete(name='Continent') +
  scale_size_continuous(name='Population (M)')
s
```
##Boxplots Galore!
```{r}
library(plotly) # install.packages('plotly')

# boxplot by continent
b = ggplot(g, aes(x=continent, y=lifeExp)) +
  geom_boxplot()
b

# match color to continents, like scatterplot
b = b +
  aes(fill=continent)
b

# drop legend, add title, update axes labels
b = b +
  theme(legend.position='none') +
  ggtitle('Life Expectancy by Continent for 2007') +
  xlab('Continent') +
  ylab('Life expectancy (years)')
b


# boxplot
ggplotly(b)

#data tables
#install.packages('DT')
library(DT)
datatable(gapminder, options = list(pageLength = 5))

###come back here:http://www.htmlwidgets.org/showcase_datatables.html
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
